# ./ios/Podfile

# Define a reusable node_require function
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})",
    __dir__
  ]).strip
end

# Load necessary scripts
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.0'
prepare_react_native_project!

# ⬇️ Include ONLY the permissions you need here
setup_permissions([
  'Bluetooth',
  'LocationWhenInUse',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BruxAway' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  pod "react-native-nordic-dfu", path: "../node_modules/react-native-nordic-dfu"

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false,
    :fabric_enabled => false
  )

  target 'BruxAwayTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
